const actionTypes = {
	TRENDING_REQUEST: 'TRENDING_REQUEST',
	GET_TRENDING_REQUEST: 'GET_TRENDING_REQUEST',
	GET_TRENDING_SUCCESS: 'GET_TRENDING_SUCCESS',
	NEW_TRENDING_REQUEST: 'NEW_TRENDING_REQUEST',
	MOVIE_REQUEST: 'MOVIE_REQUEST',
	GET_MOVIE_REQUEST: 'GET_MOVIE_REQUEST',
	GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
	GET_SEARCH_REQUEST: 'GET_SEARCH_REQUEST',
	GET_SEARCH_SUCCESS: 'GET_SEARCH_SUCCESS',
	NEW_SEARCH_REQUEST: 'NEW_SEARCH_REQUEST',
	GET_FAV_MOVIE_REQUEST: 'GET_FAV_MOVIE_REQUEST',
	GET_FAV_MOVIE_SUCCESS: 'GET_FAV_MOVIE_SUCCESS',
	GET_ERROR: 'GET_ERROR',
	ADD_FAV_ID: 'ADD_FAV_ID',
	DEL_FAV_ID: 'DEL_FAV_ID',
	CLEAR_FAVS: 'CLEAR_FAVS',
}

export default actionTypes;